### ISSUE TITLE
NameError: name 'BTN' is not defined

### ISSUE THREAD

**Issue by oliver124810** [philipl/evdevremapkeys#37]
I am trying to set up evdevremapkeys on a pretty vanilla Ubuntu 20.10 system, but I get the following error when trying to run evdevremapkeys. Any idea what could possibly be wrong ?

```
# evdevremapkeys -l
Traceback (most recent call last):
  File "/usr/local/bin/evdevremapkeys", line 33, in <module>
    sys.exit(load_entry_point('evdevremapkeys==0.1', 'console_scripts', 'evdevremapkeys')())
  File "/usr/local/bin/evdevremapkeys", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdevremapkeys-0.1-py3.8.egg/evdevremapkeys/evdevremapkeys.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.4.0-py3.8-linux-x86_64.egg/evdev/__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.4.0-py3.8-linux-x86_64.egg/evdev/device.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/evdev-1.4.0-py3.8-linux-x86_64.egg/evdev/ecodes.py", line 77, in <module>
NameError: name 'BTN' is not defined

```

**Comment by philipl** [comment]
It seems like there's something up with the binary parts of the `evdev` module. I would reinstall it.

**Comment by oliver124810** [comment]
I reinstalled it in a venv, and it solved this issue. Weird, since like I mentioned my environment is pretty standard. Thanks for the help.
